# Generated by Django 4.2.9 on 2025-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Renda Fixa, Ações, Criptomoedas etc.', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes adicionais sobre este tipo de investimento.', null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Investimento',
                'verbose_name_plural': 'Tipos de Investimento',
                'ordering': ['nome'],
            },
        ),
    ]
