# Generated by Django 4.2.9 on 2025-05-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_financialinstitution_alter_investmenttype_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstitution',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='investmenttype',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Ativo')),
                ('ticker', models.CharField(blank=True, max_length=20, verbose_name='Ticker')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Investido')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Atual')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.category')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='investments.investmenttype')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
    ]
