# Generated by Django 4.2.9 on 2025-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_financialinstitution_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('selic', 'SELIC'), ('ipca', 'IPCA'), ('cdi', 'CDI'), ('other', 'Outro')], max_length=20, verbose_name='Índice')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor (%)')),
                ('date', models.DateField(verbose_name='Data de Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice',
                'verbose_name_plural': 'Índices',
            },
        ),
    ]
