# Generated by Django 4.2.9 on 2025-05-26 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='data_operacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='investments.broker'),
        ),
    ]
