# Generated by Django 4.2.9 on 2025-05-30 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_broker_investment_criado_em_investment_data_operacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('apply', 'Apply'), ('rescue', 'Rescue')], max_length=10, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Preço')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Taxas')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['-date'], 'verbose_name': 'Índice', 'verbose_name_plural': 'Índices'},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='index',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.financialinstitution'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='data_operacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Operação'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Operação'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterUniqueTogether(
            name='index',
            unique_together={('name', 'date')},
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment'),
        ),
    ]
