# Generated by Django 4.2.9 on 2025-05-30 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_investmenttransaction_alter_index_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinstitution',
            name='parser_class',
            field=models.CharField(blank=True, help_text="Import path da classe de parser, ex: 'investments.parsers.XPParser'", max_length=200, verbose_name='Classe de Parser'),
        ),
        migrations.AddField(
            model_name='financialinstitution',
            name='signature_patterns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Strings que aparecem no PDF para identificar esta instituição', size=None),
        ),
    ]
