# Generated by Django 4.2.9 on 2025-05-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_financialinstitution_parser_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinstitution',
            name='parsing_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Defina um JSON com regex para cada campo, ex: {"data_operacao": "Data de\\\\s*Cotização\\\\s*(\\\\d{2}/\\\\d{2}/\\\\d{4})", "valor": "Valor Solicitado\\\\s*R\\\\$\\\\s*([\\\\d\\\\.\\\\,]+)", "tipo": "Operação\\\\s*(Aplicação|Resgate)"}', verbose_name='Regras de Parsing'),
        ),
    ]
